### PR TITLE
Print better test logs and disable parallel execution of tests

### PR DESCRIPTION
**Pull request by blufugen**
Some tests fail when executing in parallel

### CODE REVIEW

**Comment by erikma** [comment]
Looks like build is failing on one of the test suites, can you fix to get a green build?

**Comment by blufugen** [comment]
> Looks like build is failing on one of the test suites, can you fix to get a green build?

Stderr: [find: 'WMIC': No such file or directory]

The failing test requires WMIC module to be installed, and the Azure pipeline machines do not seem to have this.

**Comment by erikma** [comment]
Let's disable the test with a Skip="WMIC module not available on DevOps Pipelines machines"

**Comment by blufugen** [comment]
The pipeline does not pick up latest commit automatically, but instead re-uses last build's commit.

**Comment by erikma** [comment]
Re-running: Clicked on the build on the PR page which goes here: https://github.com/Microsoft/BuildXL/pull/27/checks?check_run_id=30288326

Then clicked “Re-Run All”

Let’s see if it picks up your latest commit

**Comment by erikma** [comment]
Can you rebase onto latest master? I committed https://github.com/Microsoft/BuildXL/commit/98417b99c3a875dbb62cf36dad5b6fe00e9bb1e7 that should avoid trying to run tests in helper DLLs

**Pull request merged**
