### PR TITLE
Update Distributed-Builds.md

### PR DESCRIPTION
**Pull request by olzhas**

### CODE REVIEW

**Review by dannyvv — APPROVED** [review]
The commit to change the comment looks good to me. 
Thanks for making the contribution @olzhas !

@narasamdya: Not sure why you put a bunch of other commits on top :) I skipped these as I assume they have already been reviwed internally.

**Comment by dannyvv** [comment]
@narasamdya: Can you take care cherry-picking the commit to apply it to the internal repo?

**Comment by smera** [comment]
Hello @olzhas,
Thanks for your contribution. Per our [contributing guideline](https://github.com/microsoft/BuildXL/blob/main/CONTRIBUTING.md), "Due to the overhead associated with this process, we ask that contributions are limited to substantial changes as opposed to cleanups like fixing typos". From what I can see, this PR falls under this last category, so unfortunately, we cannot take it as is.

Thanks,
Serge.

**Comment by mpysson** [comment]
Closing as per @smera's comment

**Pull request closed without merging**
