### PR TITLE
[WIP] Dummy PR for files to review for API and Schema Meeting

### PR DESCRIPTION
**Pull request by sahilmgandhi**
This is a dummy PR as per Mike's suggestion to just highlight all the files that should be reviewed to finalize the schema and APIs

### CODE REVIEW

**Comment by mpysson** [comment]
>     string FileArtifact = 2;

Should we call this "Path"?

---
Refers to: Public/Src/Tools/Xldb.Proto/StaticGraph.proto:51 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by mpysson** [comment]
>     string FileArtifact = 2;

All of these types and properties should have comments describing them. For example, should consumers expect this to be a fully rooted path or one relative to the base of their build?

---
Refers to: Public/Src/Tools/Xldb.Proto/StaticGraph.proto:51 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by mpysson** [comment]
>     string DirectoryArtifact = 2;

Directory Path?

---
Refers to: Public/Src/Tools/Xldb.Proto/StaticGraph.proto:67 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by mpysson** [comment]
>                 Console.Error.WriteLine("Could not create an accessor for RocksDB. Accessor is null! " + accessor.Failure.DescribeIncludingInnerFailures());

Should hook something similar up for the accessor's failureHandler above

---
Refers to: Public/Src/Tools/Xldb/XldbDataStore.cs:57 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by mpysson** [comment]
>                     storedEvents.Add(parser.ParseFrom(kvp.Value));

Collecting all events in memory could get out of hand based on how much the query matches. Check out the "yield" keyword in C#. You can utilize that to defer the iteration of the underlying IEnumerable returned by database.PrefixSearch and thus also defer the parsing of the raw data until consumption.

---
Refers to: Public/Src/Tools/Xldb/XldbDataStore.cs:117 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by mpysson** [comment]
>         public (IEnumerable<uint>, IEnumerable<uint>) GetProducerAndConsumersOfPath(string path, bool isDirectory)

Need documentation for the various parameters. Full path? relative ok? wildcards?

---
Refers to: Public/Src/Tools/Xldb/XldbDataStore.cs:595 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message ExtraEventDataReported{

Think about renaming (in both BXL and protobuf(

---
Refers to: Public/Src/Tools/Xldb.Proto/Events.proto:135 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message ProcessFingerprintComputationEvent{

Should we log it by default? Add exclusion list filter

---
Refers to: Public/Src/Tools/Xldb.Proto/Events.proto:263 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message BXLInvocationEvent{

Add command line to both BXL and Protobuf code

---
Refers to: Public/Src/Tools/Xldb.Proto/Events.proto:296 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> 

PipIdKey should be the value for semistableshashkey

---
Refers to: Public/Src/Tools/Xldb.Proto/StaticGraph.proto:31 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> }

Make this a string

---
Refers to: Public/Src/Tools/Xldb.Proto/StaticGraph.proto:19 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>     string Value = 1;

byte array??

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:418 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>     int64 LengthAndExistence = 1;

separate fields

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:429 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message WeakContentFingerPrint{

lowercase p

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:570 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message StrongContentFingerPrint{

lower case p

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:574 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message Fingerprint{

trace who is using it and merge with ContentHash

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:476 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message ObservedPathEntry{

Should be more information stored in here

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:578 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>     NodeId NodeId = 3;

rm -rf

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:699 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>     NodeId OtherNode = 1;

PipId

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:899 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>     uint32 Value = 3;

repeated info ... remove

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:903 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message Edge{

rm -rf

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:897 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> }

duplicated message

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:912 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> }

replace noderange with node count instead

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:928 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> }

not used

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:918 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>         public XldbDataStore(string storeDirectory,

check the version file here

---
Refers to: Public/Src/Tools/Xldb/XldbDataStore.cs:34 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>     public sealed class XldbDataStore : IDisposable

Create interface with public api surface

---
Refers to: Public/Src/Tools/Xldb/XldbDataStore.cs:17 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>         public IEnumerable<(PipType, IMessage)> GetAllScheduledPips()

redundant, since we are only doing non meta data pips

---
Refers to: Public/Src/Tools/Xldb/XldbDataStore.cs:529 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
>                     storedEvents.Add(parser.ParseFrom(kvp.Value));

We can't use yields in lambda expressions (i wanted to do this from the start). Do you have any workaround that can make it work?

---
In reply to: [529008073](https://github.com/microsoft/BuildXL/pull/843#issuecomment-529008073) [](ancestors = 529008073)

---
Refers to: Public/Src/Tools/Xldb/XldbDataStore.cs:117 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message Fingerprint{

Looked through, and i dont think we can merge it with ContentHash since ContentHash has other member variables that Fingerprint does not have

---
In reply to: [529030473](https://github.com/microsoft/BuildXL/pull/843#issuecomment-529030473) [](ancestors = 529030473)

---
Refers to: Public/Src/Tools/Xldb.Proto/EnumsAndHelperStructs.proto:476 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Comment by sahilmgandhi** [comment]
> message ExtraEventDataReported{

Do this in a separate PR in case it trickles down and touches the telemetry logger.

---
In reply to: [529023244](https://github.com/microsoft/BuildXL/pull/843#issuecomment-529023244) [](ancestors = 529023244)

---
Refers to: Public/Src/Tools/Xldb.Proto/Events.proto:135 in 99323f4. [](commit_id = 99323f4eda7d07a04fbf457400cc9b1ab3275dd0, deletion_comment = False)

**Pull request closed without merging**
